<?php

use App\Controllers\AuthController;
use App\Controllers\AttendanceController;
use App\Controllers\CompanyController;
use App\Controllers\ContractController;
use App\Controllers\DeclarationController;
use App\Controllers\DashboardController;
use App\Controllers\DepartmentController;
use App\Controllers\EmployeeController;
use App\Controllers\LeaveController;
use App\Controllers\MedicalController;
use App\Controllers\PayrollController;
use App\Controllers\PositionController;
use App\Controllers\TrainingController;
use App\Controllers\UserController;
use App\Middleware\AuthMiddleware;
use App\Middleware\RoleMiddleware;

$dashboardAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager', 'employe']];
$companyAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh']];
$employeeAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager']];
$organizationAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager']];
$contractAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager']];
$attendanceAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager', 'employe']];
$leaveAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager', 'employe']];
$medicalAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager', 'employe']];
$trainingAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh', 'manager']];
$payrollAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh']];
$declarationAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh']];
$userAccess = [AuthMiddleware::class, [RoleMiddleware::class, 'super-admin', 'admin-rh']];

$router->get('/', [DashboardController::class, 'index'], $dashboardAccess);
$router->get('/dashboard', [DashboardController::class, 'index'], $dashboardAccess);
$router->get('/dashboard/detail', [DashboardController::class, 'detail'], $dashboardAccess);
$router->get('/dashboard/export', [DashboardController::class, 'export'], $dashboardAccess);
$router->get('/companies', [CompanyController::class, 'index'], $companyAccess);
$router->get('/companies/create', [CompanyController::class, 'create'], $companyAccess);
$router->post('/companies/store', [CompanyController::class, 'store'], $companyAccess);
$router->get('/companies/show', [CompanyController::class, 'show'], $companyAccess);
$router->get('/companies/edit', [CompanyController::class, 'edit'], $companyAccess);
$router->post('/companies/update', [CompanyController::class, 'update'], $companyAccess);
$router->post('/companies/delete', [CompanyController::class, 'delete'], $companyAccess);
$router->post('/companies/status', [CompanyController::class, 'toggleStatus'], $companyAccess);
$router->post('/companies/branches/store', [CompanyController::class, 'storeBranch'], $companyAccess);
$router->post('/companies/branches/delete', [CompanyController::class, 'deleteBranch'], $companyAccess);
$router->post('/companies/subscription/update', [CompanyController::class, 'updateSubscription'], $companyAccess);
$router->get('/departments', [DepartmentController::class, 'index'], $organizationAccess);
$router->get('/departments/data', [DepartmentController::class, 'data'], $organizationAccess);
$router->post('/departments/store', [DepartmentController::class, 'store'], $organizationAccess);
$router->post('/departments/update', [DepartmentController::class, 'update'], $organizationAccess);
$router->post('/departments/delete', [DepartmentController::class, 'delete'], $organizationAccess);
$router->get('/positions', [PositionController::class, 'index'], $organizationAccess);
$router->get('/positions/data', [PositionController::class, 'data'], $organizationAccess);
$router->post('/positions/store', [PositionController::class, 'store'], $organizationAccess);
$router->post('/positions/update', [PositionController::class, 'update'], $organizationAccess);
$router->post('/positions/delete', [PositionController::class, 'delete'], $organizationAccess);
$router->get('/employees', [EmployeeController::class, 'index'], $employeeAccess);
$router->get('/employees/create', [EmployeeController::class, 'create'], $employeeAccess);
$router->post('/employees/store', [EmployeeController::class, 'store'], $employeeAccess);
$router->get('/employees/show', [EmployeeController::class, 'show'], $employeeAccess);
$router->get('/employees/edit', [EmployeeController::class, 'edit'], $employeeAccess);
$router->post('/employees/update', [EmployeeController::class, 'update'], $employeeAccess);
$router->post('/employees/archive', [EmployeeController::class, 'archive'], $employeeAccess);
$router->post('/employees/documents/upload', [EmployeeController::class, 'uploadDocument'], $employeeAccess);
$router->get('/attendance', [AttendanceController::class, 'index'], $attendanceAccess);
$router->post('/attendance/check-in', [AttendanceController::class, 'checkIn'], $attendanceAccess);
$router->post('/attendance/check-out', [AttendanceController::class, 'checkOut'], $attendanceAccess);
$router->post('/attendance/mark-absent', [AttendanceController::class, 'markAbsent'], $attendanceAccess);
$router->post('/attendance/bulk-save', [AttendanceController::class, 'bulkSave'], $attendanceAccess);
$router->post('/attendance/day/close', [AttendanceController::class, 'closeDay'], $attendanceAccess);
$router->post('/attendance/day/lock', [AttendanceController::class, 'lockDay'], $attendanceAccess);
$router->post('/attendance/day/reopen', [AttendanceController::class, 'reopenDay'], $attendanceAccess);
$router->get('/attendance/report', [AttendanceController::class, 'report'], $attendanceAccess);
$router->get('/attendance/report/export', [AttendanceController::class, 'exportReport'], $attendanceAccess);
$router->get('/leaves', [LeaveController::class, 'index'], $leaveAccess);
$router->get('/leaves/create', [LeaveController::class, 'create'], $leaveAccess);
$router->post('/leaves/store', [LeaveController::class, 'store'], $leaveAccess);
$router->get('/leaves/approval', [LeaveController::class, 'approval'], $leaveAccess);
$router->post('/leaves/types/store', [LeaveController::class, 'storeType'], $leaveAccess);
$router->post('/leaves/approve-manager', [LeaveController::class, 'approveManager'], $leaveAccess);
$router->post('/leaves/approve-hr', [LeaveController::class, 'approveHr'], $leaveAccess);
$router->post('/leaves/reject', [LeaveController::class, 'reject'], $leaveAccess);
$router->get('/medical', [MedicalController::class, 'index'], $medicalAccess);
$router->get('/medical/requests', [MedicalController::class, 'requests'], $medicalAccess);
$router->get('/medical/dependents', [MedicalController::class, 'dependents'], $medicalAccess);
$router->get('/medical/providers', [MedicalController::class, 'providers'], $medicalAccess);
$router->get('/medical/settings', [MedicalController::class, 'settings'], $medicalAccess);
$router->get('/medical/show', [MedicalController::class, 'show'], $medicalAccess);
$router->post('/medical/settings/store', [MedicalController::class, 'storeSettings'], $medicalAccess);
$router->post('/medical/dependents/store', [MedicalController::class, 'storeDependent'], $medicalAccess);
$router->post('/medical/providers/store', [MedicalController::class, 'storeProvider'], $medicalAccess);
$router->post('/medical/requests/store', [MedicalController::class, 'storeRequest'], $medicalAccess);
$router->post('/medical/requests/approve', [MedicalController::class, 'approve'], $medicalAccess);
$router->post('/medical/requests/reject', [MedicalController::class, 'reject'], $medicalAccess);
$router->post('/medical/claims/store', [MedicalController::class, 'storeClaim'], $medicalAccess);
$router->post('/medical/claims/pay', [MedicalController::class, 'payClaim'], $medicalAccess);
$router->get('/medical/voucher/pdf', [MedicalController::class, 'voucherPdf'], $medicalAccess);
$router->get('/trainings', [TrainingController::class, 'index'], $trainingAccess);
$router->get('/trainings/show', [TrainingController::class, 'show'], $trainingAccess);
$router->post('/trainings/courses/store', [TrainingController::class, 'storeCourse'], $trainingAccess);
$router->post('/trainings/sessions/store', [TrainingController::class, 'storeSession'], $trainingAccess);
$router->post('/trainings/participants/add', [TrainingController::class, 'addParticipants'], $trainingAccess);
$router->post('/trainings/attendance/save', [TrainingController::class, 'saveAttendance'], $trainingAccess);
$router->post('/trainings/finalize', [TrainingController::class, 'finalize'], $trainingAccess);
$router->get('/trainings/export', [TrainingController::class, 'export'], $trainingAccess);
$router->get('/payroll', [PayrollController::class, 'index'], $payrollAccess);
$router->get('/payroll/settings', [PayrollController::class, 'settings'], $payrollAccess);
$router->get('/payroll/simulation', [PayrollController::class, 'simulation'], $payrollAccess);
$router->post('/payroll/simulation/calculate', [PayrollController::class, 'simulate'], $payrollAccess);
$router->post('/payroll/simulation/pdf', [PayrollController::class, 'simulationPdf'], $payrollAccess);
$router->get('/payroll/create', [PayrollController::class, 'create'], $payrollAccess);
$router->post('/payroll/periods/store', [PayrollController::class, 'storePeriod'], $payrollAccess);
$router->get('/payroll/process', [PayrollController::class, 'process'], $payrollAccess);
$router->post('/payroll/calculate', [PayrollController::class, 'calculate'], $payrollAccess);
$router->post('/payroll/close', [PayrollController::class, 'close'], $payrollAccess);
$router->get('/payroll/payslip', [PayrollController::class, 'payslip'], $payrollAccess);
$router->get('/payroll/payslip/pdf', [PayrollController::class, 'pdf'], $payrollAccess);
$router->get('/payroll/export', [PayrollController::class, 'export'], $payrollAccess);
$router->post('/payroll/items/store', [PayrollController::class, 'storeItem'], $payrollAccess);
$router->post('/payroll/taxes/store', [PayrollController::class, 'storeTax'], $payrollAccess);
$router->post('/payroll/contributions/store', [PayrollController::class, 'storeContribution'], $payrollAccess);
$router->get('/payroll/settings/detail', [PayrollController::class, 'settingDetail'], $payrollAccess);
$router->post('/payroll/settings/update', [PayrollController::class, 'updateSetting'], $payrollAccess);
$router->post('/payroll/settings/delete', [PayrollController::class, 'deleteSetting'], $payrollAccess);
$router->get('/declarations', [DeclarationController::class, 'index'], $declarationAccess);
$router->get('/declarations/show', [DeclarationController::class, 'show'], $declarationAccess);
$router->post('/declarations/generate', [DeclarationController::class, 'generate'], $declarationAccess);
$router->post('/declarations/payment', [DeclarationController::class, 'payment'], $declarationAccess);
$router->post('/declarations/proof', [DeclarationController::class, 'uploadProof'], $declarationAccess);
$router->get('/declarations/pdf', [DeclarationController::class, 'pdf'], $declarationAccess);
$router->get('/declarations/export', [DeclarationController::class, 'export'], $declarationAccess);
$router->get('/contracts', [ContractController::class, 'index'], $contractAccess);
$router->get('/contracts/data', [ContractController::class, 'data'], $contractAccess);
$router->get('/contracts/create', [ContractController::class, 'create'], $contractAccess);
$router->post('/contracts/store', [ContractController::class, 'store'], $contractAccess);
$router->get('/contracts/show', [ContractController::class, 'show'], $contractAccess);
$router->get('/contracts/edit', [ContractController::class, 'edit'], $contractAccess);
$router->post('/contracts/update', [ContractController::class, 'update'], $contractAccess);
$router->post('/contracts/renew', [ContractController::class, 'renew'], $contractAccess);
$router->post('/contracts/expire', [ContractController::class, 'expire'], $contractAccess);
$router->post('/contracts/pdf/generate', [ContractController::class, 'generatePdf'], $contractAccess);
$router->post('/contracts/signed/upload', [ContractController::class, 'uploadSigned'], $contractAccess);
$router->get('/users', [UserController::class, 'index'], $userAccess);
$router->post('/users/store', [UserController::class, 'store'], $userAccess);
$router->post('/users/update', [UserController::class, 'update'], $userAccess);
$router->post('/users/status', [UserController::class, 'status'], $userAccess);
$router->post('/users/password', [UserController::class, 'password'], $userAccess);
$router->post('/users/delete', [UserController::class, 'delete'], $userAccess);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/logout', [AuthController::class, 'logout'], [AuthMiddleware::class]);
